question_data = [
{"text": "Prince Harry is taller than Prince William", "answer": "False"},
{"text": "The star sign Aquarius is represented by a tiger", "answer": "True"},
{"text": "Meryl Streep has won two Academy Awards", "answer": "False"},
{"text": "Marrakesh is the capital of Morocco", "answer": "False"},
{"text": "Idina Menzel sings 'let it go' 20 times in 'Let It Go' from Frozen", "answer": "False"},
{"text": "Waterloo has the greatest number of tube platforms in London", "answer": "True"},
{"text": "M&M stands for Mars and Moordale", "answer": "False"},
{"text": "Gin is typically included in a Long Island Iced Tea", "answer": "True"},
{"text": "The unicorn is the national animal of Scotland", "answer": "True"},
{"text": "There are two parts of the body that can't heal themselves", "answer": "False"},
{"text": "Howard Donald is the oldest member of Take That", "answer": "True"},
{"text": "The Great Wall of China is longer than the distance between London and Beijing", "answer": "True"},
{"text": "There are 219 episodes of Friends", "answer": "False"},
{"text": "'A' is the most common letter used in the English language", "answer": "False"},
{"text": "A lion's roar can be heard up to eight kilometres away", "answer": "True"},
{"text": "In Harry Potter, Draco Malfoy has no siblings", "answer": "False"},
{"text": "Louis Walsh is older than Simon Cowell", "answer": "True"},
{"text": "Monaco is the smallest country in the world", "answer": "False"},
{"text": "'What Do You Mean' was Justin Bieber's first UK number one single", "answer": "True"},
{"text": "The river Seine in Paris is longer than the river Thames in London", "answer": "True"},
{"text": "A cara cara navel is a type of orange", "answer": "True"},
{"text": "There are five different blood groups", "answer": "False"},
{"text": "Cinderella was the first Disney princess", "answer": "False"},
{"text": "ASOS stands for As Seen On Screen", "answer": "True"},
{"text": "The Battle Of Hastings took place in 1066", "answer": "True"},
{"text": "H&M stands for Hennes & Mauritz", "answer": "True"},
{"text": "Canis lupur is the scientific name for a wolf", "answer": "False"},
{"text": "K is worth four points in Scrabble", "answer": "False"},
{"text": "Alaska is the biggest American state in square miles", "answer": "True"},
{"text": "Ariana Grande is 25 or under", "answer": "False"},
{"text": "Australia is wider than the moon", "answer": "True"},
{"text": "Queen Elizabeth II is currently the second longest reigning British monarch", "answer": "False"},
{"text": "Madonna's real name is Madonna", "answer": "True"},
{"text": "Serena Williams has one more singles tennis Grand Slam titles than sister Venus", "answer": "True"},
{"text": "Alexander Fleming discovered penicillin", "answer": "True"},
{"text": "Harry Styles' middle name is Edward", "answer": "True"},
{"text": "Your 'radius' bone is in your leg", "answer": "False"},
{"text": "Coffee is made from berries", "answer": "True"},
{"text": "Drag Race's Michelle Visage is older than RuPaul", "answer": "False"},
{"text": "The only letter not in the periodic table is the letter J", "answer": "True"},
{"text": "Jordan North won I'm A Celebrity... Get Me Out Of Here! in 2020", "answer": "False"},
{"text": "The small intestine is about three-and-a-half times the length of your body", "answer": "True"},
{"text": "An octopus has three hearts", "answer": "True"},
{"text": "Thomas Edison discovered gravity", "answer": "False"},
{"text": "Walt Disney holds the record for the most Oscars", "answer": "True"},
{"text": "Spaghetto is the singular word for a piece of spaghetti", "answer": "True"},
{"text": "Venus is the hottest planet in the solar system", "answer": "True"},
{"text": "Hillary Clinton and Celine Dion are related", "answer": "False"},
{"text": "Cardi B's real name is Cardigan Backyardigan", "answer": "False"},
{"text": "Bananas are curved because they grow upwards towards the sun", "answer": "True"},
{"text": "The five rings on the Olympic flag are interlocking", "answer": "True"},
{"text": "Fish cannot blink", "answer": "True"},
{"text": "Friends star Lisa Kudrow was originally cast in Frasier", "answer": "True"},
{"text": "Goldfish have a two second memory", "answer": "False"},
{"text": "50 Cent and Charlie Chaplin were alive at the same time", "answer": "True"},
{"text": "There are 14 bones in a human foot", "answer": "False"},
{"text": "Hot and cold water sound the same when poured.", "answer": "False"},
{"text": "There have been seven million pound winners on Who Wants to Be a Millionaire.", "answer": "False"},
{"text": "Meghan Markle's first name is Rachel.", "answer": "True"},
{"text": "In Finding Nemo the protagonist is a pufferfish.", "answer": "False"},
{"text": "In a deck of cards, the king has a mustache.", "answer": "False"},
{"text": "When the two numbers on opposite sides of a dice are added together it always equals 7.", "answer": "True"},
{"text": "In the English language there is no word that rhymes with orange.", "answer": "True"},
{"text": "Hippos sweat a red substance.", "answer": "True"},
{"text": "Sex and the City star Kim Cattrall is from California.", "answer": "False"}
]
